name: core
description: core package
version: 0.0.2
homepage:
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  firebase_core:
  cloud_firestore:
    # git:
    #   url: https://github.com/firebase/flutterfire.git
    #   path: packages/cloud_firestore/cloud_firestore
    #   ref: master

  fluentui_system_icons:
  cloud_functions: 
  enhanced_cloud_firestore:
  file_saver:
  path_provider:
  muskey:
  function_tree: 
  date_format:
  intl: 
  recase:
  timeago:
  visibility_detector:
  feather_icons:
  form_builder_validators:
  video_player_media_kit:
  algeria:
  blurhash_dart:
    # path: /Users/mohamad/Desktop/projects/packages/algeria
  flutter_map: ^6.0.0-dev.3
  lib:
    # path: ../lib
    git:
     url: https://github.com/Modern-IT-Solutions/lib.git
     ref: main
  zplayer:
    # path: ../zplayer
    git:
     url: https://github.com/Modern-IT-Solutions/z-player.git
     ref: main

  cached_network_image:
  # form_builder_phone_field:
  file_picker:
  firebase_auth:
  media_cache_manager:
  flutter_local_notifications: ^16.0.0-dev.2
  firebase_analytics:
  firebase_app_check:
  firebase_crashlytics:
  universal_io:
  universal_html:
  firebase_ui_oauth_google:
  firebase_ui_oauth_apple:
  firebase_ui_auth:
  firebase_storage:
  url_launcher:
  geoflutterfire_plus: 
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  # SharedPreferences
  shared_preferences:
  google_fonts:
  gradient_borders: ^1.0.0
  puncher:
  flutter_json_view:
  photo_view: ^0.14.0
    # path: /Users/mohamad/Desktop/projects/kflutter/puncher
  latlng_picker:
    # path: /Users/mohamad/Desktop/projects/kflutter/latlng_picker
  osm_nominatim:
  motif: ^0.0.6
  image_picker: ^1.0.7
  record: ^5.0.4
  audioplayers: ^5.2.1
  fl_chart: ^0.66.2

dependency_overrides:
  http: ^1.0.0
  flutter_svg: ^2.0.6
  latlong2: ^0.9.0
  flutter_map: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.3.3
  json_serializable: ^6.6.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
